const { spawnSync } = require('child_process')
function runScan(rule) {
  const res = spawnSync('npx', ['ast-grep', 'scan', '-r', rule], { encoding: 'utf-8' })
  return (res.stdout || '').trim()
}
runScan('.rules/SelectItem.yml')
runScan('.rules/contrast.yml')
runScan('.rules/supabase-google-sso.yml')
const useAuth = runScan('.rules/useAuth.yml')
if (!useAuth) process.exit(0)
const authProvider = runScan('.rules/authProvider.yml')
if (authProvider) process.exit(0)
console.log('=== ast-grep scan -r .rules/useAuth.yml output ===')
console.log(useAuth)
console.log('')
console.log('=== ast-grep scan -r .rules/authProvider.yml output ===')
console.log(authProvider)
console.log('')
console.log('⚠️  Issue detected:')
console.log('The code uses useAuth Hook but does not have AuthProvider component wrapping the components.')
console.log('Please ensure that components using useAuth are wrapped with AuthProvider to provide proper authentication context.')
console.log('')
console.log('Suggested fixes:')
console.log('1. Add AuthProvider wrapper in app.tsx or corresponding root component')
console.log('2. Ensure all components using useAuth are within AuthProvider scope')
process.exit(0)
